Add more detailed error messages
SaraAlert/hana pull request #1
Opened 2020-11-30 19:34 UTC by ngfreiter

This PR attempts to do a few things:
* Make all existing error messages have a descriptive message
* Add more error handling for certain cases that were not getting handled. Examples of this are when `path` did not exist on certain operations, or when a `path` pointed to a child element of something like a boolean.
* More closely align the behavior of the `replace` operation with the spec. Per the spec [replace](https://tools.ietf.org/html/rfc6902#section-4.3) requires that a path exist, and this constraint was not implemented in the code. This PR adds support for that requirement.

I also updated the tests a little bit so that they would still pass. The only thing that caused tests to fail was replacing an `IndexError` with a `MissingTargetException`, besides that, all the tests continued to pass.

2020-11-30 23:01 UTC, tstrass requested changes

2020-12-01 13:17 UTC, ngfreiter commented on lib/hana.rb
> +          raise Hana::Patch::MissingTargetException, "key '#{from_key} not found"
Do you think it makes sense to just change the error message for both cases? The `KeyError` could happen if `src` is an object that doesn't have the desired key, and the `NoMethodError` could happen if `src` is pointing at a boolean or a number. So the errors have slightly different underlying causes, but the real issue in either case is that the location pointed to by the `from` parameter doesn't exist.

I think to be consistent with the addition of the "the target location does not exist", this error could be something like: "the 'from' location '<location>' does not exist". Let me know what you think.

2020-12-01 13:20 UTC, ngfreiter commented on lib/hana.rb
> +        end
This gets hit when we try to index into a string, boolean, or number. So for example, something like:
```
[
  { "op": "add", "path": "/birthDate/foo", "value": "2000-01-01" }
]
```
should hit this case, since we try to index into `birthDate`, a string.

2020-12-01 13:54 UTC, tstrass commented on lib/hana.rb
> +          raise Hana::Patch::MissingTargetException, "key '#{from_key} not found"
Yes, good call I agree.

2020-12-01 14:09 UTC, ngfreiter commented on lib/hana.rb
> +          raise Hana::Patch::MissingTargetException, "key '#{from_key} not found"
Addressed in https://github.com/SaraAlert/hana/pull/1/commits/8c1493666445f46246ef69f4644e70c01811b260

2020-12-01 14:09 UTC, ngfreiter commented on lib/hana.rb
> +      raise(MissingTargetException, "unable to find path '#{ins['path']}'") unless dest
Addressed in https://github.com/SaraAlert/hana/pull/1/commits/8c1493666445f46246ef69f4644e70c01811b260

2020-12-01 14:09 UTC, ngfreiter commented on lib/hana.rb
> +      raise(MissingTargetException, "unable to find path '#{ins['path']}'") unless dest
Addressed in https://github.com/SaraAlert/hana/pull/1/commits/8c1493666445f46246ef69f4644e70c01811b260

2020-12-01 14:09 UTC, ngfreiter commented on lib/hana.rb
> +      raise(MissingTargetException, "unable to find path '#{ins['path']}'") unless dest
Addressed in https://github.com/SaraAlert/hana/pull/1/commits/8c1493666445f46246ef69f4644e70c01811b260

2020-12-01 14:24 UTC, tstrass commented on lib/hana.rb
> +        end
Ah right I see now, thanks.

So I think there's still a case here where things could get weird. If the client sends:
``` 
{ "op": "add", "path": "/birthDate/9", "value": "1" }
```
I think this will successfully index into the value of `birthDate`, say "1985-01-01", and replace the first instance of "9" with "1", resulting in "1185-01-01". What if we added a check here that `Hash === dest`?

2020-12-01 14:51 UTC, ngfreiter commented on lib/hana.rb
> +        end
Good idea, that's safer and more clear. I'll add that.

2020-12-01 15:37 UTC, ngfreiter commented on lib/hana.rb
> +        end
I added the check to `add_op` in https://github.com/SaraAlert/hana/pull/1/commits/b851e6df861aab07f07c3bc24223d82f53cc39a0.

I considered adding a similar check to `rm_op`, but since the `key?` function is used in `rm_op` for an existing error case, and the `key?` function doesn't exist on strings, numbers, and booleans, I thought it made more sense to just catch the `NoMethodError` that happens when we call the `key?` function on those types.

2020-12-01 18:46 UTC, tstrass approved these changes
Nice!

2020-12-03 14:52 UTC, holmesie approved these changes

2020-12-03 15:18 UTC, jawalonoski approved these changes

2020-12-03 16:00 UTC, merged